# Generated by Django 4.1.7 on 2023-04-12 11:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Add_vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no', models.CharField(max_length=200)),
                ('parking_area_no', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=200)),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parking_area_no', models.CharField(max_length=200)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_limit', models.CharField(max_length=200)),
                ('parking_charge', models.DecimalField(decimal_places=2, max_digits=5)),
                ('status', models.CharField(max_length=10)),
                ('arrival_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
