# Generated by Django 4.1.7 on 2023-04-14 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spmsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='add_vehicle',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='category',
            name='action',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='add_vehicle',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
